### ISSUE TITLE
Retrieving a single still frame takes more than 6 seconds (on a wall clock)

### ISSUE THREAD

**Issue by dwrobel** [raspberrypi/libcamera-apps#123] opened 2021-10-11 18:41 UTC
Using:
- libcamera-apps@https://github.com/raspberrypi/libcamera-apps/commit/0ddf74f1a0705961bc281eb4da914ec20ce6a671
- https://github.com/libcamera-org/libcamera/commit/fa7a95bf32c6a8ee87b67159d4238cbc8e6dc3a9

to test https://github.com/raspberrypi/libcamera-apps/issues/90 showed that retrieving a single still frame takes more than 6 seconds _(on a wall clock)_:

```
$ time libcamera-jpeg -o test.jpeg
Preview window unavailable
[251:39:09.394290233] [21629]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+1-c1d703c3
[251:39:09.465335712] [21629]  INFO Camera camera.cpp:937 configuring streams: (0) 1640x1232-YUV420
[251:39:09.465482024] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt RG10 Score: 2218 (best 2218)
[251:39:09.465550245] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt RG10 Score: 2041.48 (best 2041.48)
[251:39:09.465585393] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt RG10 Score: 1500 (best 1500)
[251:39:09.465618356] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt RG10 Score: 5004.81 (best 1500)
[251:39:09.465651059] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt pRAA Score: 1718 (best 1500)
[251:39:09.465680762] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt pRAA Score: 1541.48 (best 1500)
[251:39:09.465712669] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt pRAA Score: 1000 (best 1000)
[251:39:09.465742446] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt pRAA Score: 4504.81 (best 1000)
[251:39:09.465775927] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt RGGB Score: 3218 (best 1000)
[251:39:09.465806408] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt RGGB Score: 3041.48 (best 1000)
[251:39:09.465836482] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt RGGB Score: 2500 (best 1000)
[251:39:09.465865315] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt RGGB Score: 6004.81 (best 1000)
[251:39:09.466009128] [21633]  INFO RPI raspberrypi.cpp:620 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected mode: 1640x1232-pRAA
[251:39:09.497173550] [21633]  INFO RPISTREAM rpi_stream.cpp:122 No buffers available for ISP Output0
[251:39:09.497215309] [21633]  INFO RPISTREAM rpi_stream.cpp:122 No buffers available for ISP Output0
[251:39:09.497241382] [21633]  INFO RPISTREAM rpi_stream.cpp:122 No buffers available for ISP Output0
[251:39:09.602348279] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (6 left)
[251:39:09.635673448] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (5 left)
[251:39:09.669937289] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (4 left)
[251:39:09.701826923] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (3 left)
[251:39:09.734998298] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (2 left)
[251:39:09.769024772] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (1 left)
[251:39:09.800469838] [21633]  INFO RPI raspberrypi.cpp:1636 Dropping frame at the request of the IPA (0 left)
[251:39:14.640330266] [21629]  INFO Camera camera.cpp:937 configuring streams: (0) 3280x2464-YUV420
[251:39:14.640495875] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt BG10 Score: 1500 (best 1500)
[251:39:14.640558874] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt BG10 Score: 7155.48 (best 1500)
[251:39:14.640599485] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt BG10 Score: 7244 (best 1500)
[251:39:14.640637225] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt BG10 Score: 10748.8 (best 1500)
[251:39:14.640677298] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt BA81 Score: 2500 (best 1500)
[251:39:14.640716242] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt BA81 Score: 8155.48 (best 1500)
[251:39:14.640756038] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt BA81 Score: 8244 (best 1500)
[251:39:14.640794760] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt BA81 Score: 11748.8 (best 1500)
[251:39:14.640833222] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 3280x2464 fmt pBAA Score: 1000 (best 1000)
[251:39:14.640870221] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1920x1080 fmt pBAA Score: 6655.48 (best 1000)
[251:39:14.640908721] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 1640x1232 fmt pBAA Score: 6744 (best 1000)
[251:39:14.640947294] [21633]  INFO RPI raspberrypi.cpp:122 Mode: 640x480 fmt pBAA Score: 10248.8 (best 1000)
[251:39:14.641135273] [21633]  INFO RPI raspberrypi.cpp:620 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected mode: 3280x2464-pBAA
Still capture image received

real	0m6.122s
user	0m0.385s
sys	0m0.477s
```
Could that be reduced somehow?

**Comment by davidplowman** [comment] 2021-10-12 07:08
Hi, it's by design that the preview runs for 5 seconds before capturing a frame, to give time for all the algorithms to settle and for the user to see the preview. Use the `-t` option to specify a different time (in ms), for example `libcamera-still -t 500 -o test.jpg` for a half second preview.

Alternatively you can by-pass this time completely if you can specify the exposure, gain and white balance in advance. Follow the instructions [here](https://www.raspberrypi.com/documentation/accessories/camera.html#libcamera-still) (scroll down to the part about "Very long exposures"  but substitute your own values), and the very first frame from the sensor will be captured.

Hopefully that answers everything so I'll close this, but please re-open if you'd like more explanation.

**Closed by davidplowman** 2021-10-12 07:08 UTC
